# This file was generated by GoReleaser. DO NOT EDIT.
cask "rawback" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "3e2f42ef4830b01ad1f79eb225bd5014acf4c3a79920b1cee967c7503144d6cc"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fc54ec94d48f2c9b5a5bbb1b58fac402b132efa183959e6bf6bcffa407aa47d0"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4aa41935dfb81801cbf8895896622e2d15f9e40fdf985c6745b6e35182920478"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1b633556b1091baa763b54d71c773f09c8ba8011a5e4307bcaa7588bb060e0a0"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_arm64.tar.gz"
    end
  end

  name "rawback"
  desc "Rawback CLI for managing photo libraries and uploads"
  homepage "https://rawback.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rawback"

  # No zap stanza required

  caveats <<~EOS
    Authenticate after installation:
      rawback auth

    View available commands with:
      rawback --help
  EOS
end
