# This file was generated by GoReleaser. DO NOT EDIT.
cask "rawback" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "283c7c9e44c9f8ed33adc10fd5887f8347ac44851265c17cf1f082be16d7d1af"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a96e13870e6eb726a5da7137a557b1c523b0ec4df72bf7340d32baa8f285dd97"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88f19e8c7c424a3bf4e693445f0775ae6e2bc3f77bd4dfd2b41e7e2c49d4a118"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6409de4a2a0b337f74f9194f50c51ae63b47d37981cfd1f6d41a8f9bc901ddee"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_arm64.tar.gz"
    end
  end

  name "rawback"
  desc "Rawback CLI for managing photo libraries and uploads"
  homepage "https://rawback.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rawback"

  # No zap stanza required

  caveats <<~EOS
    Authenticate after installation:
      rawback auth

    View available commands with:
      rawback --help
  EOS
end
