# This file was generated by GoReleaser. DO NOT EDIT.
cask "rawback" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "c82d829e0b88b2630dca25a5a7d5d1322c5dc9bfe425265bd049e9a68f530ea0"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "59d3e508834911967567083996e3538b10f0ee7377a4b2aa3ac58ec890345a06"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5e622f56ebba48867560b7a5c52e040366d55a1da2cec3acff03fc93e7dcefe"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b56a685627e0f069b0373e5519b8e4940fe5ead20135a0346b1f3ed94bc0286b"
      url "https://github.com/rawback-app/cli/releases/download/v#{version}/rawback_Linux_arm64.tar.gz"
    end
  end

  name "rawback"
  desc "Rawback CLI for managing photo libraries and uploads"
  homepage "https://rawback.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rawback"

  # No zap stanza required

  caveats <<~EOS
    Authenticate after installation:
      rawback auth

    View available commands with:
      rawback --help
  EOS
end
